name: First pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      id: cache
      with:
        path: ./app/node_modules
        key: node_module_cache_${{ hashFiles('./app/package-lock.json')}}
    - name: install depandancy
      if: steps.cache.output.cache-hit != 'true'
      working-directory: ./app
      run: npm install
    - name: Test
      working-directory: ./app
      run: npm run test
    - name: run lint simulator
      run: echo "test done"
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: run lint simulator
      run: echo "Linter done"
  
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      id: cache
      with:
        path: ./app/node_modules
        key: node_module_cache_${{ hashFiles('./app/package-lock.json')}}
    - name: install depandancy
      if: steps.cache.output.cache-hit != 'true'
      working-directory: ./app
      run: npm install
    - name: run build simulator
      working-directory: ./app
      run: npm run build
    - name: artifact the build
      uses: actions/upload-artifact@v3
      with:
        name: frontand-build
        path: ./app/build
  
  deploy:
    needs: [build]
    environment: test
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
      VAL_1: ${{ vars.VAR_1 }}
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: frontand-build
    - name: List artifacts
      run: ls
    - name: run lint simulator
      run: echo "deploy done ${MY_SECRET} and ${VAL_1}" && sleep 5
    - name: run lint simulator
      run: echo "deploy done ${MY_SECRET} and ${VAL_1}" && sleep 5
    - name: run lint simulator
      run: echo "deploy done ${MY_SECRET} and ${VAL_1}" && sleep 5
  