name: First pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v4
    # - name:
    #   working-directory: ./app
    #   run: npm ci
    # - name: Test
    #   working-directory: ./app
    #   run: npm run test
    - name: run lint simulator
      run: echo "test done"
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: run lint simulator
      run: echo "Linter done"
  
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - name: run buil simulator
      run: echo "build done"
  
  deploy:
    needs: [build]
    environment: test
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
      VAL_1: ${{ vars.VAL_1 }}
    runs-on: ubuntu-latest
    steps:
    - name: run lint simulator
      run: echo "deploy done ${MY_SECRET} and ${VAL_1}"
  